### ISSUE TITLE
Insufficient funds on staking leads to "please connect wallet" message

### ISSUE THREAD

**Issue by H34D** [VitaDAO/VitaDAO-web3#1]
<img width="986" alt="Screenshot 2021-06-14 at 10 18 33" src="https://user-images.githubusercontent.com/13647606/121861282-fe483480-ccf9-11eb-8416-18144ffa99b4.png">

**Comment by audieleon** [comment]
@mmahmutovic This is incorrect wording for the button under this condition. 

Could you please change the wording for this condition to "Insufficient Balance"

**Comment by theobtl** [comment]
What's currently set as the minimum amount to stake?
Not clear to me why it should be >0.

**Comment by audieleon** [comment]
The linked PR corrected this issue.
