### ISSUE TITLE
Title/Content of Proposal preview and actual page dont match

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#10]
**Describe the bug**
Sometimes, If I clicked on the preview of a proposal, a different one shows up (different title, text), lets double check if this is an issue or if we only had a confusion and put in different titles for the same proposal??

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by audieleon** [comment]
@vincentweisser This could be one of a few issues I saw. Could you add some more information, especially how to reproduce?
