### ISSUE TITLE
Logo/Main Menu is missing

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by audieleon** [comment]
@vincentweisser Could you add more information here?

**Comment by audieleon** [comment]
Is this a possible duplicate of #19
