### ISSUE TITLE
Project page is missing

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#12]
**Describe the bug**
We have to add the page for Projects we've funded like Mortens Copenhagen.

**Comment by audieleon** [comment]
@vincentweisser I believe I saw this as well, and I think it was from an incorrect proposal type on the proposal data in IPFS.

Can you confirm where you saw this, and fill our the form above? We do need to fail gracefully when a format isn't what we expect.

**Comment by vincentweisser** [comment]
I meant the project page for projects we've funded like "Copenhagen" to be listed under
