### ISSUE TITLE
Improve Responsiveness of Page (content min width etc)

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by audieleon** [comment]
@vincentweisser This appears to be an enhancement, since I believe the site still works. Though I could be wrong about that. Feel free to change it something doesn't work.

Could you add more detail here (resolutions, browsers, screenshots, etc.)?
