### ISSUE TITLE
Missing interface message if one already voted.. leads to contract error

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#15]

**Comment by audieleon** [comment]
This is a problem that actually exists in the contracts. There is no way for the VITA Holder to know if they voted - the method isn't available to the user on the staking contract. That means the UX can't tell either. 

I'm pursuing a fix on the contracts, and will update here when I have it. Until then, this is unfixable (except, possibly within the users same session, but that would require unnecessary stateful overhead I personally can't stomach).

**Comment by audieleon** [comment]
If the user confirms the transaction, they will pay gas to get an expensive error - that does show the information the UX needs above. Confirmed in the contracts that this data could be available, but isn't yet. 

![image](https://user-images.githubusercontent.com/2258619/124250077-200f2d00-daea-11eb-9e51-b44d7d0283b7.png)

**Comment by audieleon** [comment]
This is resolved by @vbarda's fix for the voting buttons.
