### ISSUE TITLE
Improving Proposal page text readability 

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#27]
**Describe the bug**
Proposal page readability and background should be improved by increasing black opacity as background, right now its a bit hard to read white text on the dna background..

Solution could be darkening the background behind text and placing it lower

**Screenshots**
<img width="1413" alt="Screenshot 2021-07-04 at 14 24 44" src="https://user-images.githubusercontent.com/32839303/124384938-e13ccb00-dcd3-11eb-8890-9fd20c4bcc20.png">

**Desktop (please complete the following information):**
Mac OS, Latest Chrome

**Comment by audieleon** [comment]
This might be a place for that styling effect of white text with a black outline, @vincentweisser. If the background it black, it'll only matter over the brightly colored elements, and will work without fading out the art.
