### ISSUE TITLE
Adding Support for More Wallets beyond MetaMask (WalletConnect etc.)

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#28]
**Describe the solution you'd like**
Think it would make sense to add support for the key other wallets beyond MetaMask, going from Uniswap ones WalletConnect, Coinbase Wallet, Formatic, Portis.. Supporting WalletConnect would probably be the most valuable given that it serves as a wallet connector to dozens other wallets and thus probably serves the most beyond MetaMask: https://registry.walletconnect.org/wallets. 
<img width="458" alt="Screenshot 2021-07-05 at 11 48 05" src="https://user-images.githubusercontent.com/32839303/124452659-dee77900-dd86-11eb-8033-514c290902f9.png">

**Comment by mmahmutovic** [comment]
Added and on Rinkeby branch
