### ISSUE TITLE
Showing Locked Period (after voting) 

### ISSUE THREAD

**Issue by vincentweisser** [VitaDAO/VitaDAO-web3#34]
**Is your feature request related to a problem? Please describe.**
On the My Wallet page, we should display the days left that tokens are locked after having voted.. 

eg.
<img width="473" alt="124498838-53d5a580-ddbd-11eb-93fa-0416293e6110" src="https://user-images.githubusercontent.com/32839303/124499285-0efe3e80-ddbe-11eb-8a68-568efd2f55d2.png">

**Comment by audieleon** [comment]
Mustafa's change gets the data on the page. doesn't look like the above. @vincentweisser can you take it from here and style it in a way that makes sense to you?
