### ISSUE TITLE
WalletConnect works, but very slowly and painfully. 

### ISSUE THREAD

**Issue by audieleon** [VitaDAO/VitaDAO-web3#49]
**Describe the bug**
Here is what I've found happens on both Rinkeby and Mainnet: 
1. Once I connect, I have to refresh, then click connect again for my balance to show up
    - There is a noticeable delay between when I refresh, and when the balances show up. 
2. I can Approve the tokens. Once I do, I get the tx in my connected wallet, and can approve it there. 
    - The transaction takes 10-15 seconds to show up in the connected wallet
    - IT TAKES FOREVER for the state to change to where I can stake. (Around 3-4 minutes)
3. Once I see the Stake button activate. I click it and wait about 30 seconds. Then the tx shows in my connected wallet
    - As soon as the tx shows, I get a "please connect wallet" message in the ui and the wallet balances disappear. 
    - I can approve the transaction through my wallet though.
4. Once the transaction clears, if I refresh the page and reconnect my wallet. I can see the staked tokens.

**To Reproduce**
Steps and description of what happens above

**Expected behavior**
The UX should respond, transactions should show up fairly quickly (within a couple seconds) once they are confirmed, and the user should NOT have to ever refresh to see correct state. 

**Additional Information**
I modified the environment variables to use the existing infura endpoint, and to not shift based on network (rather to count on deployment environment vars). 

The wallet connect stuff sort of works, but I think some timing or event listener stuff is missing. The UI responds to injected stuff, but waits for polling or in some cases, manual refreshes for the wallet connect stuff.

**Comment by audieleon** [comment]
Might be worth looking [here:](https://codesandbox.io/examples/package/@web3-react/walletconnect-connector).

There are several examples, and it seems like they differ somewhat from what we have.

**Comment by schmackofant** [comment]
For me, the connecting works pretty instant, tried it successfully with Argent, Ledger Live, and Gnosis Safe apps.

The WalletConnect details (account address, handshake ID, etc.) get save to LocalStorage, but it doesn't they're used to reconnect if you refresh the page and the react app gets initialized again.

**Comment by audieleon** [comment]
The linked PR does not fix this issue.

**Comment by JohannesHa** [comment]
I think a quick fix for now could be to add loading spinners on the buttons (I think the buttons already had that logic but no event listeners were implemented?). That would already improve the user experience by quite a bit.

For me it directly changes the button states/labels when the transaction is confirmed. Here's a demo video of how long the staking process takes for me at the moment:

https://user-images.githubusercontent.com/26834619/125815203-b6a040f7-4fc9-48c8-840f-6e7f1a1186c9.mov

**Comment by JohannesHa** [comment]
Yep. Just a few lines of code were missing…

A success message or some confetti after the staking and not just an updating of the label would make it even more enjoyable😄

https://user-images.githubusercontent.com/26834619/125825946-9f310790-1cd1-4990-9995-85bc146303bb.mp4
